### ISSUE TITLE
Update jest version to latest

### ISSUE THREAD

**Issue by wiesnery** [nicoespeon/jest-extended-snapshot#6]
Could you update the peer jest dependency to also allow the use with current version. Maybe a `>23.x` would do the job.

Thanks for publishing this idea <3

**Comment by nicoespeon** [comment]
That's fair, I'll fix that so you can use it with latest versions.

**Comment by nicoespeon** [comment]
Should be fixed with the latest version. Let me know if I messed it up 😉

**Comment by wiesnery** [comment]
Thanks for the fast support 😃
